# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Grocy UI
version: "1.15.0"
init: false
slug: grocy_ui
description: A streamlined UI for Grocy
url: "https://github.com/RossMcMillan92/grocy-ui"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
ports:
  3820/tcp: 3820
startup: services
boot: auto