# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Grocy UI
version: 37
slug: grocy_ui
description: A streamlined UI for Grocy
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
ports:
  3820/tcp: 3820
schema:
image: "ghcr.io/home-assistant/{arch}-addon-example"
